version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:jdk-stretch
    steps:
      -checkout
      - run: |
          echo "$(git tag -l --points-at HEAD)" > ~/circle_tag.txt
      -restore_cache:
          key: circleci-jnote-{{ checksum "pom.xml"}}
      -run:
          name: download remaining dependencies
          command: mvn dependency:go-offline
      -save_cache:
          paths:
            - ~/m2
          key: circleci-jnote-{{ checksum "pom.xml" }}
      -run:
          name: test
          command: mvn test
