version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch

    steps:
      - checkout

      - run: |
          echo "$(git tag -l --points-at HEAD)" > ~/circle_tag.txt

      - restore_cache:
          key: circleci-werekitten-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline
